### ISSUE TITLE
PJAX/[Mock Single-page-app] capabilities

### ISSUE THREAD

**Issue by kylesloper** [slinkity/slinkity#160]
## Is your feature request related to a problem? Please describe.
Whilst I do understand that rugged and both accessible SPA systems are hard to implement, I think that they would be a real benefit to the growth of Slinkity and opening this issue is a place for others to chime in with their ideas. At the moment with my current PJAX setup, `reactDOM` loses interactivity when opening a new page. 

I imagine this is due to the React lifecycle in which all components are rendered on document load. This could be fixed by re-rendering all components in a Slinkity project each time a page is loaded however I think this is a little too in-efficient especially in spite of the new additional component frameworks coming soon 🎉😅

## Describe the solution you'd like
Does anyone propose an efficient method to re-initialize the `Slinkity-mount` instead. This is the best idea I have at the moment as it is likely to scale well with the project.

## Describe alternatives you've considered
*Currently using `Swup` for all the PJAX workings but if anyone suggests something else, would be happy to explore.*

**Comment by kylesloper** [comment]
And some stuff to help :)

- [Example repo](https://github.com/kylesloper/slinkity-pjax)
- [Live demo](https://mf-slinkity-pjax.surge.sh/)

**Comment by sadeghbarati** [comment]
List of Page-Transitions:

1. [barba.js](https://barba.js.org/)
2. swup
3. [starting-blocks](https://github.com/rezozero/starting-blocks)
4. [highway.js](https://highway.js.org/)
5. [hotwire/turbo](https://turbo.hotwired.dev/)
6. [modularload](https://github.com/modularorg/modularload)
7. [smoothState.js](https://github.com/miguel-perez/smoothState.js/)

**Comment by sadeghbarati** [comment]
I noticed now in the demo that `react`, `vue`, `svelte` and `vanilla` components need to `reinitialize` after page switch

Each of these page transitions libs has its own implementation for reinitialize components:

- Swup + Gia
- Turbo + Stimulus
and ...

@Holben888 

A while ago I saw page-transition implementation for slinkity in

https://github.com/slinkity/slinkity#feature-set

but now is gone what is your plan for this feature?

**Comment by kylesloper** [comment]
Yes I explained in the OP that a re-initialization of the `component mount` is where we need to head. I have spoken to Ben privately about the removal of page transitions - from what I understood it is a very heavy feature to work on with many factors needed to be taken into account. I have ran a few experiments concerning this recently; think we shall just leave this one to the open source community to suggest the best method forward❤️

**Comment by Holben888** [comment]
Thanks for the investigation @sadeghbarati! Yes, as @kylesloper said, there are a number of considerations to an SPA setup. The mission of the project definitely changed since that initial roadmap as well. Our focus: maintain your existing 11ty workflow as much as possible, and add helpers for a) styles and b) components on top. Mock SPAs are more of an added bonus.

_That said,_ I'd like to revive this initiative once I find a path forward 😁 There are a couple DOM diffing libraries that could help with component re-mounting:
1. [millionjs](https://millionjs.org/) - their core maintainer reached out to improve our HMR capabilities, and I noticed they're working on an SPA-like router as well
2. [micromorph](https://www.npmjs.com/package/micromorph) - maintained by Nate Moore, a core maintainer of [Astro](https://astro.build/). He's been experimenting with SPA-in-Astro and noticed a similar component mounting problem. It sounds like Micromorph could scratch a similar itch to Million, and it's a battle-tested solution to Astro's HMR. I plan to work closely with him to see what's possible.

☝️ If anyone wants to jerry-rig a solution from either of these tools, go ahead! Just know that a) serverless support and b) more hydration "modes" are higher on the list for me at the moment.

**Comment by aidenybai** [comment]
I'd love to take on this issue, unless anything has popped up recently that has changed your mind @Holben888

**Comment by bholmesdev** [comment]
@aidenybai Absolutely, feel free to jump in! I'd definitely suggest trying micromorph (linked above) and potentially referencing [Astro's SPA pull request](https://github.com/withastro/astro/pull/2899). These could definitely inform our approach.

**Comment by visini** [comment]
Having re-hydration when using swup/barba/... would be just fantastic 🤗

**Comment by bholmesdev** [comment]
@visini I'll be writing a Swup x [Astro](https://astro.build/) guide in the next couple weeks! I have a feeling we'll have similar guidance for Slinkity. Once I confirm that's the case, I'll add to our docs 👍

**Comment by bholmesdev** [comment]
Closing after all these years. Today, I would recommend Chrome's built in view transitions for these capabilities. We've used a minimal wrapper in Astro that could be implemented in any HTML head tag. [web.dev has a great guide on the subject.](https://developer.chrome.com/docs/web-platform/view-transitions)
