### ISSUE TITLE
Server options, https, liveReload, domDiff?

### ISSUE THREAD

**Issue by cozarkd** [slinkity/slinkity#238]
## What feature were you trying to use?

I'm trying to understand how this approach manages server. Should I use Eleventy new server? Are you using Browsersync?
With that info I guess I can do some research about where to link my local certificate.

## Where did our docs fail you?

I guess a section for server info would be helpful, specifically to integrate Slinkity in already started projects.

**Comment by bholmesdev** [comment]
Thanks for the report @cozarkd! We are using 11ty's built-in server rather than browsersync, so you should check out 11ty's new server here.

However, I will share that the Slinkity project is no longer maintained. To make this clear to new users, I have archived the repository, and I have updated the project README to reflect the current status.

If the community would like to fork and keep Slinkity alive, all code is open and MIT licensed. I apologize for the radio silence, but I hope this clarifies everything!
