### ISSUE TITLE
Switch to pnpm

### ISSUE THREAD

**Issue by Holben888** [slinkity/slinkity#57]
**Is your feature request related to a problem? Please describe.**
We currently use "plain" npm for everything in our repo. This comes with a few problems:
- slowest installation times of all available options
- nothing to help with managing workspaces, should we need them

**Describe the solution you'd like**
I'd like to choose something faster and/or sexier for our project. [pnpm](https://pnpm.io/) seems to fit the bill according to this thread from [Jared Palmer](https://twitter.com/jaredpalmer/status/1449846044259348486)!

**Describe alternatives you've considered**
Yarn v1 seems like a tried-and-true choice for speeding up local installs. Still, it suffers from:
- unique keywords that differ from `npm` like `add` instead of `i`. Some like this, but I personally think it hurts the beginner-friendliness for new contributors
- it's aging by comparison to Yarn v2 (which is a _hassle_ to set up). Worth investigating v3 though.

**Update: decided on Yarn 3**
We've decided to use Yarn 3 instead given our team's existing familiarity with Yarn 1. Redwood's decision to use Yarn 3 gives us some confidence as well!

**Comment by ajcwebdev** [comment]
First question is what specific `npm` commands are we using and what is the `pnpm` equivalent? Looking through the repo I see one place we're using `npm link` and another place we're using `npm run build` to run a babel script. Are there any other places we're specifically using npm aside from basics like `npm install`?

## `pnpm` Replacements

|npm command|pnpm equivalent|
|---------------|-----------------|
|[npm link](https://docs.npmjs.com/cli/v7/commands/npm-link)|[pnpm link](https://pnpm.io/cli/link)|
|[npm run](https://docs.npmjs.com/cli/v7/commands/npm-run-script)|[pnpm run](https://pnpm.io/cli/run)|
|[npm install](https://docs.npmjs.com/cli/v7/commands/npm-install)|[pnpm install](https://pnpm.io/cli/install)|

### Differences between `npm run` and `pnpm run`

* By default, pnpm doesn't run arbitrary `pre` and `post` hooks for user-defined scripts (such as `prestart`). This behavior, inherited from `npm`, caused scripts to be implicit rather than explicit, obfuscating the execution flow. It also led to surprising executions with `pnpm serve` also running `pnpm preserve`.

### Differences between `pnpm install` and `pnpm add`

* [`pnpm add`](https://pnpm.io/cli/add) installs a package and any packages that it depends on. By default, any new package is installed as a production dependency. If executed in a workspace, the command will first try to check whether other projects in the workspace use the specified package. If so, the already used version range will be installed.
* [`pnpm install`](https://pnpm.io/cli/install) is used to install all dependencies for a project. Inside a workspace, `pnpm install` installs all dependencies in all the projects. If you want to disable this behavior, set the `recursive-install` setting to `false`.

## Yarn 3

Redwood has been working on [migrating from Yarn 1 to Yarn 3](https://github.com/redwoodjs/redwood/pull/3154) and the results have been promising. As Yarn 3 continues to be rolled out we should test it out in addition to testing out `pnpm`. Once both options have been evaluated we can make the decision on whether to migrate away from `npm` to either option.

**Comment by Holben888** [comment]
Okay, I think I'm switching back in favor of `pnpm` now that I've used it for a bit. A few reasons:
- **We now encourage usage of `pnpm` to make local debugging simpler** via `overrides`. Note: this is also a feature in npm v8.3.0, but I'm less comfortable encouraging people use such a new npm release
- **Members of the Vite server already use `pnpm`.** I reach out to the Vite community quite a lot when debugging issues, and I'd like to use the same tools they are all familiar with. Projects using `pnpm` include Vite itself and SvelteKit (Astro doessss use `yarn` admittedly)

In the end, I'm sure either tool is excellent! Just sharing my thoughts here.

**Comment by AlexMunoz** [comment]
Hey @Holben888 Would it be okay if I worked on it?

**Comment by Holben888** [comment]
@AlexMunoz Yeah absolutely! Also worth exploring: using `pnpm` workspaces to share dependencies between packages (just `/packages/slinkity` and `/www` right now, but we have more soon to come). Let me know anything else you'd recommend if you have pnpm experience.
